### ISSUE TITLE
How can getters / setters be used?

### ISSUE THREAD

**Issue by leisim** [dart-lang/json_serializable#285]
Hi,
Is it possible to use getters and setters with this library? 

```dart
@JsonSerializable()
class TestModel {
  @JsonKey(name: "Name")
  String get someGetter => "My Name";

  String _name;

  @JsonKey(name: "Name")
  set someSetter(name) => _name = name + " Something";
}
```

**Comment by kevmoo** [comment]
Yes! That should work.

Are you finding issues?

**Comment by leisim** [comment]
@kevmoo Yes I get an exception when I try to generate code for the `TestModel` above:

```
...

[INFO] Running build...
[SEVERE] json_serializable on lib/models/test_model.dart:
Error running JsonSerializableGenerator
NoSuchMethodError: The getter 'metadata' was called on null.
Receiver: null
Tried calling: metadata

...
```

**Comment by kevmoo** [comment]
Could you run with `--verbose` and include the full output?

**Comment by leisim** [comment]
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 363ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 178ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 562ms

[INFO] Build:Running build...
[INFO] Build:Running build completed, took 16ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 62ms

[SEVERE] json_serializable on lib/models/test_model.dart (cached):
Error running JsonSerializableGenerator
NoSuchMethodError: The getter 'metadata' was called on null.
Receiver: null
Tried calling: metadata
dart:core                                                              Object.noSuchMethod
package:source_gen/src/type_checker.dart 84:17                         TypeChecker.firstAnnotationOfExact
package:json_serializable/src/json_key_with_conversion.dart 23:23      _from
package:json_serializable/src/json_key_with_conversion.dart 135:36     new JsonKeyWithConversion
package:json_serializable/src/helper_core.dart 43:7                    HelperCore.jsonKeyFor
package:json_serializable/src/json_serializable_generator.dart 198:18  _GeneratorHelper._generate.<fn>
dart:collection                                                        __CompactLinkedHashSet&_HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.fold
package:json_serializable/src/json_serializable_generator.dart 194:41  _GeneratorHelper._generate

[SEVERE] Build:
Failed after 112ms
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:185:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:142:32)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:348:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#10     Future._complete (dart:async/future_impl.dart:476:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

**Comment by kevmoo** [comment]
Try only annotating the getter and see what happens...

**Comment by kevmoo** [comment]
This is a pretty gnarly edge case.

Why can't you just name the getter and setter than same thing?

**Comment by leisim** [comment]
Sorry, I don't understand the question :/

**Comment by kevmoo** [comment]
Why not name the getter/setter than same thing?

```dart
@JsonSerializable()
class TestModel {
  @JsonKey(name: "Name")
  String get myProperty => "My Name";

  String _name;

  set myProperty(name) => _name = name + " Something";
}
```

Then you get this...

```dart
TestModel _$TestModelFromJson(Map<String, dynamic> json) {
  return TestModel()..myProperty = json['Name'] as String;
}

Map<String, dynamic> _$TestModelToJson(TestModel instance) =>
    <String, dynamic>{'Name': instance.myProperty};
```

**Comment by leisim** [comment]
Okay, that works. But it would be nice if it would be possible to have only a getter or in my case only a setter...

**Comment by kevmoo** [comment]
@leisim – would you mind writing out what source you wish you could write – and then what you expect to be generated?

**Comment by leisim** [comment]
@kevmoo No problem. We have very complex and often badly structured data. Here is a sample from the project I'm currently working on:

```dart
@JsonSerializable()
class LogisticsItem {
  @JsonKey(ignore: true)
  bool logisticsChecked;

  @JsonKey(ignore: true)
  bool logisticsOK;

  @JsonKey(name: "LogistikTeileInOrdnung")
  set _jsonLogisticsProcessed(String processed) {
    logisticsChecked = processed != null && processed != "null";
    logisticsOK = processed == "true";
  }
}
```

This should generate the following:
```dart
LogisticsItem _$LogisticsItemFromJson(Map<String, dynamic> json) {
  return LogisticsItem().._jsonLogisticsProcessed = json['LogistikTeileInOrdnung'] as String;
}

Map<String, dynamic> _$LogisticsItemToJson(LogisticsItem instance) =>
    <String, dynamic>{};
```

Also it would be very cool if there was an option in `@JsonSerializable` like `ignoreNotAnnotated` to only use annotated properties. This would spare writing `@JsonKey(ignore: true)` for all unused properties.

**Comment by kevmoo** [comment]
@leisim – it seems you don't really need/want `toJson` right?

How about this:

```dart
@JsonSerializable(createToJson: false)
class LogisticsItem {
  final bool logisticsChecked;
  final bool logisticsOK;

  LogisticsItem(@JsonKey(name: 'LogistikTeileInOrdnung') String processed)
      : logisticsChecked = processed != null && processed != 'null',
        logisticsOK = processed == 'true';
}
```

Which generates:

```dart
LogisticsItem _$LogisticsItemFromJson(Map<String, dynamic> json) {
  return LogisticsItem(json['LogistikTeileInOrdnung'] as String);
}
```

**Comment by kevmoo** [comment]
... ☝️ won't work now – but we could make it work

**Comment by leisim** [comment]
This would be sooo cool. Way better than using setters 👍

**Comment by kevmoo** [comment]
In the mean time:

```dart

@JsonSerializable(createToJson: false)
class LogisticsItem {
  final bool logisticsChecked;
  final bool logisticsOK;

  @JsonKey(name: 'LogistikTeileInOrdnung')
  final String processed;

  LogisticsItem(this.processed)
      : logisticsChecked = processed != null && processed != 'null',
        logisticsOK = processed == 'true';

  factory LogisticsItem.fromJson(Map<String, dynamic> json) =>
      _$LogisticsItemFromJson(json);
}
```

works fine. You have the extra `processed` field – but it's better than nothing.

**Comment by leisim** [comment]
Wow thanks this is perfect!
