### ISSUE TITLE
How to work with derived?

### ISSUE THREAD

**Issue by ValeriusGC** [dart-lang/json_serializable#365]
This works well:
```
@JsonSerializable()
class Pt {
  final double x;
  final double y;
  Pt(this.x, this.y);
  factory Pt.fromJson(Map<String, dynamic> json) => _$PtFromJson(json);
  Map<String, dynamic> toJson() => _$PtToJson(this);
}

@JsonSerializable()
class Derived {
  final Pt value;
  Derived(this.value);
  factory Derived.fromJson(Map<String, dynamic> json) => _$DerivedFromJson(json);
  Map<String, dynamic> toJson() => _$DerivedToJson(this);
}
```
but this fails:
```
@JsonSerializable()
class Base {
  final Pt value;

  Base(this.value);

  factory Base.fromJson(Map<String, dynamic> json) => _$BaseFromJson(json);
  Map<String, dynamic> toJson() => _$BaseToJson(this);
}
@JsonSerializable()
class Pt {
  final double x;
  final double y;

  Pt(this.x, this.y);

  factory Pt.fromJson(Map<String, dynamic> json) => _$PtFromJson(json);

  Map<String, dynamic> toJson() => _$PtToJson(this);
}

@JsonSerializable()
class Derived extends Base {

  Derived(value) : super(value);

  factory Derived.fromJson(Map<String, dynamic> json) => _$DerivedFromJson(json);

  Map<String, dynamic> toJson() => _$DerivedToJson(this);
}

void main() {
  final d = Derived(Pt(1.12, 2.22));
  final dJson = _encode(d);
  print(dJson);
  final d2 = Derived.fromJson(json.decode(dJson) as Map<String, dynamic>);
  print(_encode(d2));
}

 ---> Error:
Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Pt'
#0      new Derived (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:32:26)
#1      _$DerivedFromJson (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.g.dart:26:10)
#2      new Derived.fromJson (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:34:58)
#3      main (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:43:22)

```

**Comment by denkuy** [comment]
I am getting a linter error
> error: The argument type 'dynamic' can't be assigned to the parameter type 'Pt'. (argument_type_not_assignable ...)

You are missing the type in the `Derived` constructor, it should be `Derived(Pt value) : super(value)`.

```dart
void main() {
  print('** encode');
  final d1 = Derived(Pt(1.12, 2.22));
  final d1Map = _$DerivedToJson(d1);
  final d1Json = json.encode(d1Map);
  print("map:  $d1Map\njson: $d1Json");

  print('** decode');
  var decodeMap = Derived.fromJson(d1Map);
  print('map: ${decodeMap.value.x} - ${decodeMap.value.y}');

  var decodeJson = Derived.fromJson(json.decode(d1Json) as Map<String, dynamic>);
  print('json: ${decodeJson.value.x} - ${decodeJson.value.y}');
}
```
