### ISSUE TITLE
How to inherit from generic class?

### ISSUE THREAD

**Issue by ValeriusGC** [dart-lang/json_serializable#366]
i tried my best according https://github.com/dart-lang/json_serializable/issues/145#issue-321065515
but have no success.
my code is:

```
@JsonSerializable()
class Pt {
  final double x;
  final double y;

  Pt(this.x, this.y);

  factory Pt.fromJson(Map<String, dynamic> json) => _$PtFromJson(json);

  Map<String, dynamic> toJson() => _$PtToJson(this);
}

//@JsonSerializable()
abstract class Base<T> {
  @JsonKey(fromJson: _dataFromJson, toJson: _dataToJson)
  final T value;

  Base(this.value);

//  factory Derived.fromJson(Map<String, dynamic> json) => _$DerivedFromJson(json);
//
//  Map<String, dynamic> toJson() => _$DerivedToJson(this);

  static T _dataFromJson<T, S, U>(Map<String, dynamic> input, [S other1, U other2]) => input['value'] as T;

  static Map<String, dynamic> _dataToJson<T, S, U>(T input, [S other1, U other2]) => {'value': input};
}

@JsonSerializable()
class Ptable extends Base<Pt> {
  Ptable(value) : super(value);

  factory Ptable.fromJson(Map<String, dynamic> json) => _$PtableFromJson(json);

  Map<String, dynamic> toJson() => _$PtableToJson(this);
}

void main() {
  final p = Ptable(Pt(2.12, 4.22));
  final pJson = _encode(p);
  print(pJson);
  final p2 = Ptable.fromJson(json.decode(pJson) as Map<String, dynamic>);
  print(_encode(p2));
}

String _encode(Object object) => const JsonEncoder.withIndent(' ').convert(object);
```
and error is:
```
Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Pt'
#0      new Ptable (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:37:25)
#1      _$PtableFromJson (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.g.dart:17:10)
#2      new Ptable.fromJson (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:39:57)
#3      main (file:///home/valerius/DevProj/Idea/Samples/Mine/Flutter/undart/bin/json.dart:54:21)
```
if i commented or uncommented `@JsonSerializable()` on `Base` class it has no result.

**Comment by denkuy** [comment]
same issue as in https://github.com/dart-lang/json_serializable/issues/365#issuecomment-452416251

Make `Ptable(Pt value) : super(value);` the constructor. Also you should probably drop @JsonKey(fromJson: _dataFromJson, toJson: _dataToJson). If T is serializable, then it will automatically call fromJson() when injecting it into the derived class constructor.

**Comment by kevmoo** [comment]
Does the comment from @denkuy help, @ValeriusGC ?
