### ISSUE TITLE
failed build

### ISSUE THREAD

**Issue by alyyasser** [dart-lang/json_serializable#551]
im not sure if this is bug in json_serializable or not, i received this error today when running `flutter pub run build_runner build`.

```
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5680:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5645:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 926:67                     ClassElementForLink_Class._computeInterfaceType
package:analyzer/src/summary/link.dart 824:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1643:7                     CompilationUnitElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3985:12                    LibraryElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3685:15                    LibraryCycleNode.link
package:analyzer/src/summary/link.dart 3625:7                     LibraryCycleDependencyWalker.evaluate
package:analyzer/src/summary/link.dart 2230:13                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2249:18                    DependencyWalker.walk
package:analyzer/src/summary/link.dart 3658:42                    LibraryCycleForLink.ensureLinked
package:analyzer/src/summary/link.dart 4190:35                    Linker.link
package:analyzer/src/summary/link.dart 312:74                     _relink
package:analyzer/src/summary/link.dart 126:3                      link
package:analyzer/src/dart/analysis/library_context.dart 220:25    LibraryContext.load.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 219:12    LibraryContext.load
package:analyzer/src/dart/analysis/library_context.dart 98:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1439:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1380:28            AnalysisDriver._computeUnitElement.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1378:20            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 997:34             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 1931:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 1865:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 192:19        BuildOptions.create
package:build_runner/src/generate/build.dart 85:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool/build/entrypoint/build.dart 22:22                      main
```

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:244:5)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
Flutter 1.10.14 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 1946fc4da0 (13 days ago) • 2019-10-07 15:23:31 -0700
Engine • revision 1d62160fdb
Tools • Dart 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)
```

```
build_runner: ^1.7.1
json_serializable: ^3.2.3
```

**Comment by kevmoo** [comment]
Which version of pkg:analyzer from pubspec.lock?

**Comment by alyyasser** [comment]
```
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.38.2"
```

**Comment by alyyasser** [comment]
ah, found the fix in here: https://github.com/dart-lang/build/issues/2509

update `build_resolvers` to latest version using `flutter packages pub upgrade`.

im closing the issue now. thanks
